name: "Storms.watch Prod"
on:
  push:
    tags:
      - release-*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - name: Restore Yarn Workspaces
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache Next.js Bundle
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn export
        env:
          API_URL: "https://storms.watch"

      - name: Deploy To Netlify
        uses: nwtgck/actions-netlify@v1.2.0
        with:
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          functions-dir: ./built-functions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./netlify.toml
          production-deploy: true
          publish-dir: ./.next
        env:
          ADMIN_PASSPHRASE: ${{ secrets.ADMIN_PASSPHRASE }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN  }}
          NETLIFY_SITE_ID: ${{ secrets.STORMS_WATCH_PROD_NETLIFY_SITE_ID }}
